In [9]:
# Pega os lembretes novos na planilha

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd

scope = [
    'https://spreadsheets.google.com/feeds',
    'https://www.googleapis.com/auth/drive'
]

creds = ServiceAccountCredentials.from_json_keyfile_name('secret.json', scope)
client = gspread.authorize(creds)

spreadsheet = client.open_by_key("1gjz0hk8dL0rbqzTfHGLbzwXnA-h8AVxZtgffCbseDIk")
sheet = spreadsheet.sheet1

data = sheet.get_all_records()
df = pd.DataFrame(data)
df = df.loc[:, (df != '').any(axis=0)]

df.rename(columns={"Tipo de Pedido": "tipo_pedido"}, inplace=True)
df["num_processo"] = df["num_processo"].str.strip()
if 'tipo_pedido' not in df.columns and 'tipo de pedido' in df.columns:
    df.rename(columns={'tipo de pedido': 'tipo_pedido'}, inplace=True)

s = df['tipo_pedido']
mask = s.notnull() & (s.astype(str).str.strip() != '')
df = df[mask].copy()

df = df[['unidade', 'num_processo', 'tipo_pedido']].copy()
df

    unidade               num_processo              tipo_pedido
0   SRD1CIV  5004629-20.2024.8.21.0069                    @1184
1   SRD1CIV  5001789-42.2021.8.21.0069                    @1184
2   SRD1CIV  5000457-79.2017.8.21.0069                    @1184
3   SRD1CIV  5004583-31.2024.8.21.0069            @acordofiscal
4   SRD1CIV  5004410-41.2023.8.21.0069            @acordofiscal
5   SRD1CIV  5004319-14.2024.8.21.0069            @acordofiscal
6   SRD1CIV  5004253-34.2024.8.21.0069            @acordofiscal
7   SRD1CIV  5004229-06.2024.8.21.0069            @acordofiscal
8   SRD1CIV  5004117-37.2024.8.21.0069            @acordofiscal
9   SRD1CIV  5003867-04.2024.8.21.0069            @acordofiscal
10  SRD1CIV  5003375-46.2023.8.21.0069            @acordofiscal
11  SRD1CIV  5003351-52.2022.8.21.0069            @acordofiscal
12  SRD1CIV  5002969-25.2023.8.21.0069            @acordofiscal
13  SRD1CIV  5000200-93.2013.8.21.0069            @acordofiscal
14  SRD1CIV  5002105-16.2025.8.21.0069         @acordoproccomum
15  SRD1CIV  5001757-66.2023.8.21.0069         @acordoproccomum
16  SRD1CIV  5001334-09.2023.8.21.0069         @acordoproccomum
17  SRD1CIV  5001285-65.2023.8.21.0069         @acordoproccomum
18  SRD1CIV  5002635-20.2025.8.21.0069            @arquivamento
19  SRD1CIV  5002377-49.2021.8.21.0069            @arquivamento
20  SRD1CIV  5000373-97.2025.8.21.0069            @arquivamento
21  SRD1CIV  5000099-85.2015.8.21.0069            @arquivamento
22  SRD1CIV  5000055-47.2007.8.21.0069            @arquivamento
23  SRD1CIV  5000025-55.2020.8.21.0069            @arquivamento
24  SRD1CIV  5002389-29.2022.8.21.0069      @embargosdeclaração
25  SRD1CIV  5000723-85.2025.8.21.0069      @embargosdeclaração
26  SRD1CIV  5000545-54.2016.8.21.0069      @embargosdeclaração
27  SRD1CIV  5004573-84.2024.8.21.0069      @embargosmonitorios
28  SRD1CIV  5001513-06.2024.8.21.0069      @embargosmonitorios
29  SRD1CIV  5001401-42.2021.8.21.0069      @embargosmonitorios
30  SRD1CIV  5003741-22.2022.8.21.0069                 @infojud
31  SRD1CIV  5003683-19.2022.8.21.0069                 @infojud
32  SRD1CIV  5003355-55.2023.8.21.0069                 @infojud
33  SRD1CIV  5003291-79.2022.8.21.0069                 @infojud
34  SRD1CIV  5002411-24.2021.8.21.0069                 @infojud
35  SRD1CIV  5001551-91.2019.8.21.0069                 @infojud
36  SRD1CIV  5000189-64.2013.8.21.0069                 @infojud
37  SRD1CIV  5000020-53.2008.8.21.0069                 @infojud
38  SRD1CIV  5000003-80.2009.8.21.0069                 @infojud
39  SRD1CIV  5004215-56.2023.8.21.0069  @medidasexpropriatórias
40  SRD1CIV  5002489-18.2021.8.21.0069  @medidasexpropriatórias
41  SRD1CIV  5004555-97.2023.8.21.0069                 @renajud
42  SRD1CIV  5003736-63.2023.8.21.0069                 @renajud
43  SRD1CIV  5003195-30.2023.8.21.0069                 @renajud
44  SRD1CIV  5003166-14.2022.8.21.0069                 @renajud
45  SRD1CIV  5003131-20.2023.8.21.0069                 @renajud
46  SRD1CIV  5002316-91.2021.8.21.0069                 @renajud
47  SRD1CIV  5000495-13.2025.8.21.0069                 @renajud
48  SRD1CIV  5000355-91.2016.8.21.0069                 @renajud
49  SRD1CIV  5000096-81.2025.8.21.0069                 @renajud
50  SRD1CIV  5004516-03.2023.8.21.0069                @whatsapp
51  SRD1CIV  5002856-37.2024.8.21.0069                @whatsapp
52  SRD1CIV  5002749-56.2025.8.21.0069                @whatsapp
53  SRD1CIV  5001961-42.2025.8.21.0069                @whatsapp

In [10]:
df

    unidade               num_processo              tipo_pedido
0   SRD1CIV  5004629-20.2024.8.21.0069                    @1184
1   SRD1CIV  5001789-42.2021.8.21.0069                    @1184
2   SRD1CIV  5000457-79.2017.8.21.0069                    @1184
3   SRD1CIV  5004583-31.2024.8.21.0069            @acordofiscal
4   SRD1CIV  5004410-41.2023.8.21.0069            @acordofiscal
5   SRD1CIV  5004319-14.2024.8.21.0069            @acordofiscal
6   SRD1CIV  5004253-34.2024.8.21.0069            @acordofiscal
7   SRD1CIV  5004229-06.2024.8.21.0069            @acordofiscal
8   SRD1CIV  5004117-37.2024.8.21.0069            @acordofiscal
9   SRD1CIV  5003867-04.2024.8.21.0069            @acordofiscal
10  SRD1CIV  5003375-46.2023.8.21.0069            @acordofiscal
11  SRD1CIV  5003351-52.2022.8.21.0069            @acordofiscal
12  SRD1CIV  5002969-25.2023.8.21.0069            @acordofiscal
13  SRD1CIV  5000200-93.2013.8.21.0069            @acordofiscal
14  SRD1CIV  5002105-16.2025.8.21.0069         @acordoproccomum
15  SRD1CIV  5001757-66.2023.8.21.0069         @acordoproccomum
16  SRD1CIV  5001334-09.2023.8.21.0069         @acordoproccomum
17  SRD1CIV  5001285-65.2023.8.21.0069         @acordoproccomum
18  SRD1CIV  5002635-20.2025.8.21.0069            @arquivamento
19  SRD1CIV  5002377-49.2021.8.21.0069            @arquivamento
20  SRD1CIV  5000373-97.2025.8.21.0069            @arquivamento
21  SRD1CIV  5000099-85.2015.8.21.0069            @arquivamento
22  SRD1CIV  5000055-47.2007.8.21.0069            @arquivamento
23  SRD1CIV  5000025-55.2020.8.21.0069            @arquivamento
24  SRD1CIV  5002389-29.2022.8.21.0069      @embargosdeclaração
25  SRD1CIV  5000723-85.2025.8.21.0069      @embargosdeclaração
26  SRD1CIV  5000545-54.2016.8.21.0069      @embargosdeclaração
27  SRD1CIV  5004573-84.2024.8.21.0069      @embargosmonitorios
28  SRD1CIV  5001513-06.2024.8.21.0069      @embargosmonitorios
29  SRD1CIV  5001401-42.2021.8.21.0069      @embargosmonitorios
30  SRD1CIV  5003741-22.2022.8.21.0069                 @infojud
31  SRD1CIV  5003683-19.2022.8.21.0069                 @infojud
32  SRD1CIV  5003355-55.2023.8.21.0069                 @infojud
33  SRD1CIV  5003291-79.2022.8.21.0069                 @infojud
34  SRD1CIV  5002411-24.2021.8.21.0069                 @infojud
35  SRD1CIV  5001551-91.2019.8.21.0069                 @infojud
36  SRD1CIV  5000189-64.2013.8.21.0069                 @infojud
37  SRD1CIV  5000020-53.2008.8.21.0069                 @infojud
38  SRD1CIV  5000003-80.2009.8.21.0069                 @infojud
39  SRD1CIV  5004215-56.2023.8.21.0069  @medidasexpropriatórias
40  SRD1CIV  5002489-18.2021.8.21.0069  @medidasexpropriatórias
41  SRD1CIV  5004555-97.2023.8.21.0069                 @renajud
42  SRD1CIV  5003736-63.2023.8.21.0069                 @renajud
43  SRD1CIV  5003195-30.2023.8.21.0069                 @renajud
44  SRD1CIV  5003166-14.2022.8.21.0069                 @renajud
45  SRD1CIV  5003131-20.2023.8.21.0069                 @renajud
46  SRD1CIV  5002316-91.2021.8.21.0069                 @renajud
47  SRD1CIV  5000495-13.2025.8.21.0069                 @renajud
48  SRD1CIV  5000355-91.2016.8.21.0069                 @renajud
49  SRD1CIV  5000096-81.2025.8.21.0069                 @renajud
50  SRD1CIV  5004516-03.2023.8.21.0069                @whatsapp
51  SRD1CIV  5002856-37.2024.8.21.0069                @whatsapp
52  SRD1CIV  5002749-56.2025.8.21.0069                @whatsapp
53  SRD1CIV  5001961-42.2025.8.21.0069                @whatsapp

In [11]:
# Reseta a tabela

import sqlite3
db = "urcaciv.db"
conn = sqlite3.connect(f'{db}')
cursor = conn.cursor()

cursor.execute(f"DELETE FROM lembretes_to_do")
conn.commit()

conn.close()

print("Todos os registros da tabela 'lembretes_to_do' foram apagados.")

Todos os registros da tabela 'lembretes_to_do' foram apagados.

In [12]:
from datetime import datetime

df["created_at"] = datetime.now().strftime("%d/%m/%Y")
df["dt_lembrete"] = None

print(df)
df.to_sql("lembretes_to_do", "sqlite:///urcaciv.db", if_exists="append", index=False)

    unidade               num_processo              tipo_pedido  created_at  \
0   SRD1CIV  5004629-20.2024.8.21.0069                    @1184  11/11/2025
1   SRD1CIV  5001789-42.2021.8.21.0069                    @1184  11/11/2025
2   SRD1CIV  5000457-79.2017.8.21.0069                    @1184  11/11/2025
3   SRD1CIV  5004583-31.2024.8.21.0069            @acordofiscal  11/11/2025
4   SRD1CIV  5004410-41.2023.8.21.0069            @acordofiscal  11/11/2025
5   SRD1CIV  5004319-14.2024.8.21.0069            @acordofiscal  11/11/2025
6   SRD1CIV  5004253-34.2024.8.21.0069            @acordofiscal  11/11/2025
7   SRD1CIV  5004229-06.2024.8.21.0069            @acordofiscal  11/11/2025
8   SRD1CIV  5004117-37.2024.8.21.0069            @acordofiscal  11/11/2025
9   SRD1CIV  5003867-04.2024.8.21.0069            @acordofiscal  11/11/2025
10  SRD1CIV  5003375-46.2023.8.21.0069            @acordofiscal  11/11/2025
11  SRD1CIV  5003351-52.2022.8.21.0069            @acordofiscal  11/11/2025
12  SRD1CIV  5002969-25.2023.8.21.0069            @acordofiscal  11/11/2025
13  SRD1CIV  5000200-93.2013.8.21.0069            @acordofiscal  11/11/2025
14  SRD1CIV  5002105-16.2025.8.21.0069         @acordoproccomum  11/11/2025
15  SRD1CIV  5001757-66.2023.8.21.0069         @acordoproccomum  11/11/2025
16  SRD1CIV  5001334-09.2023.8.21.0069         @acordoproccomum  11/11/2025
17  SRD1CIV  5001285-65.2023.8.21.0069         @acordoproccomum  11/11/2025
18  SRD1CIV  5002635-20.2025.8.21.0069            @arquivamento  11/11/2025
19  SRD1CIV  5002377-49.2021.8.21.0069            @arquivamento  11/11/2025
20  SRD1CIV  5000373-97.2025.8.21.0069            @arquivamento  11/11/2025
21  SRD1CIV  5000099-85.2015.8.21.0069            @arquivamento  11/11/2025
22  SRD1CIV  5000055-47.2007.8.21.0069            @arquivamento  11/11/2025
23  SRD1CIV  5000025-55.2020.8.21.0069            @arquivamento  11/11/2025
24  SRD1CIV  5002389-29.2022.8.21.0069      @embargosdeclaração  11/11/2025
25  SRD1CIV  5000723-85.2025.8.21.0069      @embargosdeclaração  11/11/2025
26  SRD1CIV  5000545-54.2016.8.21.0069      @embargosdeclaração  11/11/2025
27  SRD1CIV  5004573-84.2024.8.21.0069      @embargosmonitorios  11/11/2025
28  SRD1CIV  5001513-06.2024.8.21.0069      @embargosmonitorios  11/11/2025
29  SRD1CIV  5001401-42.2021.8.21.0069      @embargosmonitorios  11/11/2025
30  SRD1CIV  5003741-22.2022.8.21.0069                 @infojud  11/11/2025
31  SRD1CIV  5003683-19.2022.8.21.0069                 @infojud  11/11/2025
32  SRD1CIV  5003355-55.2023.8.21.0069                 @infojud  11/11/2025
33  SRD1CIV  5003291-79.2022.8.21.0069                 @infojud  11/11/2025
34  SRD1CIV  5002411-24.2021.8.21.0069                 @infojud  11/11/2025
35  SRD1CIV  5001551-91.2019.8.21.0069                 @infojud  11/11/2025
36  SRD1CIV  5000189-64.2013.8.21.0069                 @infojud  11/11/2025
37  SRD1CIV  5000020-53.2008.8.21.0069                 @infojud  11/11/2025
38  SRD1CIV  5000003-80.2009.8.21.0069                 @infojud  11/11/2025
39  SRD1CIV  5004215-56.2023.8.21.0069  @medidasexpropriatórias  11/11/2025
40  SRD1CIV  5002489-18.2021.8.21.0069  @medidasexpropriatórias  11/11/2025
41  SRD1CIV  5004555-97.2023.8.21.0069                 @renajud  11/11/2025
42  SRD1CIV  5003736-63.2023.8.21.0069                 @renajud  11/11/2025
43  SRD1CIV  5003195-30.2023.8.21.0069                 @renajud  11/11/2025
44  SRD1CIV  5003166-14.2022.8.21.0069                 @renajud  11/11/2025
45  SRD1CIV  5003131-20.2023.8.21.0069                 @renajud  11/11/2025
46  SRD1CIV  5002316-91.2021.8.21.0069                 @renajud  11/11/2025
47  SRD1CIV  5000495-13.2025.8.21.0069                 @renajud  11/11/2025
48  SRD1CIV  5000355-91.2016.8.21.0069                 @renajud  11/11/2025
49  SRD1CIV  5000096-81.2025.8.21.0069                 @renajud  11/11/2025
50  SRD1CIV  5004516-03.2023.8.21.0069                @whatsapp  11/11/2025
51  SRD1CIV  5002856-37.2024.8.21.0069                @whatsapp  11/11/2025
52  SRD1CIV  5002749-56.2025.8.21.0069                @whatsapp  11/11/2025
53  SRD1CIV  5001961-42.2025.8.21.0069                @whatsapp  11/11/2025

   dt_lembrete
0         None
1         None
2         None
3         None
4         None
5         None
6         None
7         None
8         None
9         None
10        None
11        None
12        None
13        None
14        None
15        None
16        None
17        None
18        None
19        None
20        None
21        None
22        None
23        None
24        None
25        None
26        None
27        None
28        None
29        None
30        None
31        None
32        None
33        None
34        None
35        None
36        None
37        None
38        None
39        None
40        None
41        None
42        None
43        None
44        None
45        None
46        None
47        None
48        None
49        None
50        None
51        None
52        None
53        None

54